cc1 roffdata
if errorlevel 1 goto done
cc2 roffdata
if errorlevel 1 goto done
cc3 -n roffdata
if errorlevel 1 goto done
cc4 roffdata
if errorlevel 1 goto done
cc1 roff4
if errorlevel 1 goto done
cc2 roff4
if errorlevel 1 goto done
cc3 -n roff4
if errorlevel 1 goto done
cc4 roff4
if errorlevel 1 goto done
cc1 roff41
if errorlevel 1 goto done
cc2 roff41
if errorlevel 1 goto done
cc3 -n roff41
if errorlevel 1 goto done
cc4 roff41
if errorlevel 1 goto done
cc1 roff42
if errorlevel 1 goto done
cc2 roff42
if errorlevel 1 goto done
cc3 -n roff42
if errorlevel 1 goto done
cc4 roff42
if errorlevel 1 goto done
cc1 roff43
if errorlevel 1 goto done
cc2 roff43
if errorlevel 1 goto done
cc3 -n roff43
if errorlevel 1 goto done
cc4 roff43
if errorlevel 1 goto done
cc1 roff44
if errorlevel 1 goto done
cc2 roff44
if errorlevel 1 goto done
cc3 -n roff44
if errorlevel 1 goto done
cc4 roff44
if errorlevel 1 goto done
cc1 roff45
if errorlevel 1 goto done
cc2 roff45
if errorlevel 1 goto done
cc3 -n roff45
if errorlevel 1 goto done
cc4 roff45
if errorlevel 1 goto done
cc1 roff46
if errorlevel 1 goto done
cc2 roff46
if errorlevel 1 goto done
cc3 -n roff46
if errorlevel 1 goto done
cc4 roff46
if errorlevel 1 goto done
cc1 roff47
if errorlevel 1 goto done
cc2 roff47
if errorlevel 1 goto done
cc3 -n roff47
if errorlevel 1 goto done
cc4 roff47
if errorlevel 1 goto done
a:link roff4+roffdata+roff41+roff42+roff43+roff44+roff45+roff46+roff47,,/map,a:c86s2n
:done
