C88 ROFFDATA
if errorlevel 1 goto done
C88 ROFF4
if errorlevel 1 goto done
C88 ROFF41
if errorlevel 1 goto done
C88 ROFF42
if errorlevel 1 goto done
C88 ROFF43
if errorlevel 1 goto done
C88 ROFF44
if errorlevel 1 goto done
C88 ROFF45
if errorlevel 1 goto done
C88 ROFF46
if errorlevel 1 goto done
C88 ROFF47
if errorlevel 1 goto done
bind ROFF4 ROFFDATA ROFF41 ROFF42 ROFF43 ROFF44 ROFF45 ROFF46 ROFF47
:done
