To
Ebnet Software
D-8000 MÅnchen 70
Passauer Strasse 2 b
West Germany

REGISTRATION/ PURCHASE ORDER - Software utility C-WINDOW
------------------------------------------------------------

Please send me (us) the software utility C-WINDOW for a charge
of $ 49.--.


I take the folowing payment:

   (  ) cheque payment
   (  ) transfer to the following bank account:
        Postgiroamt MÅnchen       
        West Germany
        bank number 700 100 80
        account number 418194-800
   (  ) cash on deliver
        (  ) in Germany                 $  3.--
        (  ) from abroad                $  6.--

disc format:
   (  ) 5.25 inch disc 
   (  ) 3.5  inch disc                  $  2.--

For a registrated user you will get an information of a new
program release automatically. You can order it in an update 
service for the special price of $ 25.--.

User support is possible for registrated users exclusively.

Sender:





Date/signature:

.............................
