/*
HEADER:         CUG241;
TITLE:          Simple weather predictor expert system to demonstrate
                the IFRUN, ANDTHENRUN, etc., keywords. 
DATE:           12/30/85;
VERSION:
DESCRIPTION:   "Source code for a simple Expert System.";
KEYWORDS:       Artificial Intelligence, expert systems, weather predictor;
SYSTEM:         MS-DOS or UNIX System V;
FILENAME:       WEATHER.H;
WARNINGS:      "User-supported, non-commercial"
AUTHORS:        George Hageman; 
COMPILERS:      Microsoft C V3.00 or UNIX System V Portable C Compiler;
REFERENCES:     ;
ENDREF
*/

#define	NORTH		1
#define NORTH_EAST	2
#define EAST		3
#define SOUTH_EAST	4
#define SOUTH		5
#define SOUTH_WEST	6
#define WEST		7
#define NORTH_WEST	8

#define STEADY		1
#define RISE_SLOW	2
#define RISE_FAST	3
#define FALL_SLOW	4
#define FALL_FAST	5


