@pagefooting(left "09/22/81 -[BAD]", right "-@value(page)-")
@pageheading(left "Amethyst Users Group - Program/Extension Submittal Form")

If  you have any comments on this  form,  please forward
them to the Amethyst Users Group.

Please  fill out this form for all material  submitted  to
the Amethyst Users Group. It will assist us in preparing your
contribution for circulation and in helping people select
programs. 

Send  the contributions with the completed  forms 
to:@address(Amethyst User's Group
P.O. Box 8173
University Station
Austin, Texas 78712)
Phone inquiries can be directed to Barry A. Dobyns
(512)441-94