xsub
clink symtab storage args misc string file rawfile misc
toolib1
toolib2
nd line arguments in sys_args[] and
puts the number of command line arguments in sys_narg.
It redirects I/O if requested on the command line.
This is done by calling _assign() which in turn updates
the arrays sys_spec [], sys_bufp [] and sys_bufn [].
