ren toolib2.brl=toolib2.crl
era *.crl
ren toolib2.crl=toolib2.brl
cc1 file.bds
cc1 rawfile.bds
cc1 toolib1.bds
cc1 args.bds
cc1 string.bds
cc1 misc.bds
cc1 convert.bds
cc1 date.bds
string.bds
cc1 misc.bds

	if (fd == SYS_TERM) {
		BDS_pchahe command line.
This is done by calling _assign() which in turn updates
the arrays sys_spec [], sys_bufp [] and sys_bufn [].
