background 1
tag $ p7
tag # pr7
tag & pr7 stat
tag % ph6 topic
#ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»$
#º Panels for C, Version 2.3                        B.C. Systems, Box 781202  º$
#º Copyright 1989-1991 J. Brown                      Wichita, KS  67278-1202  º$
#ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼$
 °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
 °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
 °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
 °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
 °°°°°°°°°°°°°°°°°°°°°°°°ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿°°°°°°°°°°°°°°°°°°°°°°°°
 °°°°°°°°°°°°°°°°°°°°°°°°³         Help Menu          ³°°°°°°°°°°°°°°°°°°°°°°°°
 °°°°°°°°°°°°°°°°°°°°°°°°ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´°°°°°°°°°°°°°°°°°°°°°°°°
 °°°°°°°°°°°°°°°°°°°°°°°°³%About Panels for C        $³°°°°°°°°°°°°°°°°°°°°°°°°
 °°°°°°°°°°°°°°°°°°°°°°°°³%Executing a Panels Program$³°°°°°°°°°°°°°°°°°°°°°°°°
 °°°°°°°°°°°°°°°°°°°°°°°°³%Panel Design              $³°°°°°°°°°°°°°°°°°°°°°°°°
 °°°°°°°°°°°°°°°°°°°°°°°°³%Programming with Panels   $³°°°°°°°°°°°°°°°°°°°°°°°°
 °°°°°°°°°°°°°°°°°°°°°°°°³%Compilation and Linkage   $³°°°°°°°°°°°°°°°°°°°°°°°°
 °°°°°°°°°°°°°°°°°°°°°°°°³%Exit help                 $³°°°°°°°°°°°°°°°°°°°°°°°°
 °°°°°°°°°°°°°°°°°°°°°°°°ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ°°°°°°°°°°°°°°°°°°°°°°°°
 °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
 °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
 °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
 °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
 °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
 °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
&                                                                              $
