#define F1       0x3b00
#define F2       0x3c00
#define F3       0x3d00
#define F4       0x3e00
#define F5       0x3f00
#define F6       0x4000
#define F7       0x4100
#define F8       0x4200
#define F9       0x4300
#define F10      0x4400
#define F11      0x8500
#define F12      0x8600

#define F13      0x5400         /* Shift F1  */
#define F14      0x5500         /* Shift F2  */
#define F15      0x5600         /* Shift F3  */
#define F16      0x5700         /* Shift F4  */
#define F17      0x5800         /* Shift F5  */
#define F18      0x5900         /* Shift F6  */
#define F19      0x5a00         /* Shift F7  */
#define F20      0x5b00         /* Shift F8  */
#define F21      0x5c00         /* Shift F9  */
#define F22      0x5d00         /* Shift F10 */
#define F23      0x8700         /* Shift F11 */
#define F24      0x8800         /* Shift F12 */

#define HOME     0x4700
#define END      0x4f00

#define UP       0x4800
#define LEFT     0x4b00
#define RIGHT    0x4d00
#define DOWN     0x5000
#define PGUP     0x4900
#define PGDN     0x5100

#define INS      0x5200
#define DEL      0x5300
#define ENTER       13
#define NENTER   0xe00d         /* Enter on the numeric keypad */
#define CENTER      10          /* Control-enter */
#define RTAB         9
#define LTAB     0x0f00
#define BS           8
#define ESC         27
