;This file contains the second of three patches to the 
;source code for FLTLIB that enable use of the AMD9511 
;(Intel 8231A) for floating point multiply/divide and 
;MATHLIB functions.
;
;N.T.Carnevale 8/84.
;
;Use the following code to replace the four DW's that 
;starting in the source for FLTLIB at Ftab:
;
;See accompanying documentation.  Other useful information
;is in my article "Faster floating point math," which appeared
;on pp.46-54 of the Nov/Dec 1985 issue of Micro/Systems Journal.
;
; C/80 3.0 (7/7/83) - (c) 1983 Walter Bilofsky - used by permission
;
Ftab:	DW	fadd.
	DW	fsub		;next two addresses not used
;	DW	fpmul
;	DW	fpdiv
;
;END OF FL2.MAC
