: SAMPLE OUTLINE FOR COMPILATION "SCRIPT", "BATCH FILE", ETC.
: Makx pgm file(s).c  --  compile file(s) to produce  pgm.x
:							run pgm.x <pgm.in >pgm.out
:							cmp pgm.out pgm.tst
:							rm pgm.o pgm.x
: Makxnt -- same compile, but no test file
: Maktry pgm file(s).c -- compile file(s) with #define TRYMAIN into pgm
:							(same run, cmp, rm)
: Mako file.c  --  compile-only, into object code

Makx accnt accnt.c 
Makx arith arith.c 
Makx asst asst.c 
Makx asst2 asst2.c 
Makx badpow badpow.c
Makx bdrill bdrill.c 
Makxnt bits bits.c
Makx blast blast.c 
Makx blast2 blast2.c 
Makx cap cap.c 
Makx cap2 cap2.c 
Makx codes1 codes1.c 
Makx codes2 codes2.c 
Makx codes3 codes3.c 
Makx codes4 codes4.c 
Makxnt copy copy.c 
Makx copy2 copy2.c 
Makx dmpdem dmpdem.c
Makx fact fact.c 
Maktry factl factl.c 
Makx fast fast.c 
Makx getbn getbn.c 
Makx getbn2 getbn2.c 
Makx gettt gettt.c
Makx guess guess.c 
Makx guess2 guess2.c 
Makx hello hello.c 
Makx hello2 hello2.c 
Makx hello3 hello3.c 
Makx hello4 hello4.c 
Makx hello5 hello5.c 
Makx inits inits.c
Makx loadtt loadtt.c
Makx maxmin maxmin.c 
Makx mortg mortg.c 
Makx mortg2 mortg2.c 
Mako nfrom 
Makx powdem powdem.c 
Makx pr2a pr2a.c 
Makx pr2b pr2b.c 
Makx prsam prsam.c 
Mako rand 
Makx recpt1 recpt1.c 
Makx recpt2 recpt2.c 
Makx recpt3 recpt3.c receip.c 
Makx revers revers.c 
Makx shuf52 shuf52.c nfrom.c  
Makx sizes sizes.c 
Makx slow slow.c 
Makxnt string string.c
Mako strlen 
Mako strscn
Makx tower tower.c pegs.c
Makx vacat vacat.c
Makx xy x.c ysub.c 
