#define LEFT       0
#define DOWN_LEFT  1
#define DOWN       2
#define DOWN_RIGHT 3
#define RIGHT      4
#define UP_RIGHT   5
#define UP         6
#define UP_LEFT    7
#define BOTTOM_LEFT     0x00
#define BOTTOM_CENTER   0x04
#define BOTTOM_RIGHT    0x01
#define TOP_LEFT        0x03
#define TOP_CENTER      0x06
#define TOP_RIGHT       0x02
#define LEFT_CENTER     0x05
#define RIGHT_CENTER    0x07
#define CLEAR_CELL      0x10
#define FILL_CELL       0x20
#define INVERSE_CELL    0x30
#define WRITE           0x00
#define NO_WRITE        0x08
#define AUTO_MOVE       0x0000
#define FIX_MOVE        0x0100
#define VAR_MOVE        0x0200

