'\" Revision Level 
'\" Last Delta     12-21-86
.TH DSZ 1 OMEN
.SH NAME
dsz \- YMODEM, ZMODEM file transfer subprogram
.SH SYNOPSIS
.B dsz
.RB [ "port N" ]
.RB [ "speed S" ]
.RB [ d ]
.RB [ "restrict" ]
.I command
.SH DESCRIPTION
Dsz
uses the YMODEM or ZMODEM error correcting batch protocol to transfer
files over a serial port with a variety of programs.
Dsz is designed to be called from a communications program or bulletin board
to perform file transfers.

Dsz
uses its own modem I/O.
The original interrupt vector
and UART interrupt configuration are restored on normal exit.
Dsz expects its standard output to point to the console or a logging file,
not a modem port.
.PP
The available commands are:
.PP
.PD 0
.TP
.B "port N"
select port N (n = 1,2,3 or 4)
Default is port 1 (COM1) or read from the
.B DSZPORT
dos environment variable.
.TP
.B "speed S"
Set specified speed, default is current speed.
.TP
.B d
Disables carrier dropout monitoring, for modems that do not properly
drive the "Data Carrier Detect" input on the PC.
.TP
.B LARG
Convert ARG to lowercase, then parse arg.
.TP
.B restrict
Restrict pathnames to current disk and directory tree.
.TP
.B sz
[-Vabnpr+y] [PREFIX=p | ONAME=n] afn ...
.TP
.B sb
[-Vk] [PREFIX=p | ONAME=n] afn ...
.TP
.B rz
[-Vabnpr+y]
.TP
.B rz
[-Vabnpr+y] file1 file2 ...
(filename override)
.TP
.B rb
[-Vab+y]
.TP
.B rb
[-Vab+y] file1 file2 ...
(filename override)
.TP
.B -V
Dsiplay debugging information.
More V's give more detailed information.
.PD
.ne 6
.SH EXAMPLES
dsz sz -r b:zcom*.arc c:foo.bar

dsz port 2 speed 19200 restrict rz

dsz rz -y newprog.arc
.SH SEE ALSO
Consult the
Professional-YAM manual
or
ZCOMMDOC.ARC
chapter "Options for File Transfers"
for option meanings.
.SH NOTES
Dsz sets the UART shift register to 8 bits no parity; the original parity
setting is lost.

Dsz may be freely used and copied, but not modified or sold
without the written permission of Omen Technology Inc.
