/*
        HEADER:         CUG000.09;
        TITLE:          BOOLEAN;
        DATE:           Mar 89;
        DESCRIPTION:    Boolean Type Header File;
        VERSION:        1.0;
        FILENAME:       BOOLEAN.H;
        SEE-ALSO:       TSP.C, NN.C, POPT.C, 2OPT.C, HYBRID.C, 3OPT.C, FN.C,
                        NODELIST.H, TSP.H,
                        BLDMTX.C, PRTMTX.C, TIME.C;
        AUTHORS:        Kevin E. Knauss;
*/

typedef char         BOOLEAN;

#define TRUE         1
#define FALSE        0
