
        o     o           o     o           o     o         o     o
       / .   . \         /.     .\         / .   . \        |.   .|
      /         \       / .     . \       /   . .   \       | . . |
     oÄ Ä Ä Ä Ä Äo     oÄ Ä Ä Ä Ä Äo     oÄ Ä Ä.Ä Ä Äo      |  .  |
          . .             .     .             . .           | . . |
           .              .     .            .   .          |.   .|
           o              oÄÄÄÄÄo           oÄÄÄÄÄo         o     o

           a.                b.                c.              d.

a. point proximity, b. chain proximity, c. chain proximity and orientation,
and d. chain orientation in place.

                   Figure 1. Ä Tour Improvement Techniques.

