                                                      TIME      TOUR   PERCENT
                                             TOUR   IN TICKS  IMPROVED  FROM
                                            LENGTH (.055 SEC)    BY    OPTIMUM
                                            ÄÄÄÄÄÄ   ÄÄÄÄÄÄ   ÄÄÄÄÄÄ   ÄÄÄÄÄÄ
10 Cities   Optimum = 378           N.N.  |    417 |      1 |    ÄÄÄ |   10.3 |
   Karg and Thompson (6)            PÄOpt |    395 |      2 |     22 |    4.5 |
                                    2ÄOpt |    381 |      1 |     36 |    0.8 |
   Input in 10 ticks.               Hybrid|    378 |      5 |     39 | OPTIMAL|
                                    3ÄOpt |    378 |      6 |     39 | OPTIMAL|
                                          |        |        |        |        |
                                    Rev.  |    417 |      1 |    ÄÄÄ |   10.3 |
                                    PÄOpt |    378 |      4 |     39 | OPTIMAL|
                                    2ÄOpt |    381 |      2 |     36 |    0.8 |
                                    Hybrid|    378 |      4 |     39 | OPTIMAL|
                                    3ÄOpt |    381 |      6 |     36 |    0.8 |
                                          |        |        |        |        |
                                    F.N.  |    582 |      2 |    ÄÄÄ |   54.0 |
                                    PÄOpt |    395 |      2 |    187 |    4.5 |
                                    2ÄOpt |    381 |      2 |    201 |    0.8 |
                                    Hybrid|    378 |      3 |    204 | OPTIMAL|
                                    3ÄOpt |    387 |     12 |    195 |    2.4 |
                                          |        |        |        |        |
20 Cities   Optimum = 246           N.N.  |    367 |      7 |    ÄÄÄ |   49.2 |
   G.A. Croes                       PÄOpt |    313 |     13 |     54 |   27.2 |
   Found in Roberts and Flores (9)  2ÄOpt |    246 |     16 |    121 | OPTIMAL|
                                    Hybrid|    255 |     23 |    112 |    3.7 |
   Input in 36 ticks.               3ÄOpt |    246 |    260 |    121 | OPTIMAL|
                                          |        |        |        |        |
                                    Rev.  |    367 |      7 |    ÄÄÄ |   49.2 |
                                    PÄOpt |    304 |     13 |     63 |   23.6 |
                                    2ÄOpt |    267 |      7 |    100 |    8.5 |
                                    Hybrid|    265 |     28 |    102 |    7.7 |
                                    3ÄOpt |    258 |    148 |    109 |    4.9 |
                                          |        |        |        |        |
                                    F.N.  |   1668 |      7 |    ÄÄÄ |  578.0 |
                                    PÄOpt |    306 |     27 |   1362 |   24.4 |
                                    2ÄOpt |    276 |     14 |   1392 |   12.2 |
                                    Hybrid|    260 |     40 |   1408 |    5.7 |
                                    3ÄOpt |    246 |    140 |   1422 | OPTIMAL|
                                          |        |        |        |        |
25 Cities   Optimum = 1,711         N.N.  |   2037 |     11 |    ÄÄÄ |   19.1 |
   Held and Karp (5)                PÄOpt |   1873 |     24 |    164 |    9.5 |
                                    2ÄOpt |   1711 |     19 |    326 | OPTIMAL|
   Input in 58 ticks.               Hybrid|   1736 |     33 |    301 |    1.5 |
                                    3ÄOpt |   1763 |    293 |    274 |    3.0 |
                                          |        |        |        |        |
                                    Rev.  |   2037 |     11 |    ÄÄÄ |   19.1 |
                                    PÄOpt |   1763 |     36 |    274 |    3.0 |
                                    2ÄOpt |   1711 |     18 |    326 | OPTIMAL|
                                    Hybrid|   1748 |     35 |    289 |    2.2 |
                                    3ÄOpt |   1719 |    300 |    318 |    0.5 |
                                          |        |        |        |        |
                                    F.N.  |   6445 |     12 |    ÄÄÄ |  276.7 |
                                    PÄOpt |   1940 |     26 |   4505 |   13.4 |
                                    2ÄOpt |   1719 |     24 |   4726 |    0.5 |
                                    Hybrid|   1886 |     45 |   4559 |   10.2 |
                                    3ÄOpt |   1780 |    394 |   4665 |    4.0 |
                   Figure 2. Ä 10, 20, and 25 City Results.
