                                  REFERENCES

1    Bellmore, M. and George L. Nemhauser.  "The Traveling Salesman Problem: A 
Survey," Operations Research, XVI, no. 3 (1968), 538Ä558.

2    Christofides, Nicos and Samuel Eilon.  "Algorithms for LargeÄscale 
Travelling Salesman Problems," Operational Research Quarterly, XXIII, no. 4 
(1972), 511Ä518.

3    Croes, A. G.  "A Method for Solving TravelingÄSalesman Problems,"
Operations Research, VI (1958), 791Ä812.

4    Edmonds, Jack.  "Matroids and the Greedy Algorithm," Mathematical
Programming, I, no. 1 (1971), 127Ä136.

5    Held, Michael and Richard M Karp.  "A Dynamic Programming Approach to 
Sequencing Problems," Journal of the Society for Industrial and Applied 
Mathematics, X, no. 1 (1962), 196Ä210.

6    Karg, Robert L. and Gerald L. Thompson.  "A Heuristic Approach to Solving 
Travelling Salesman Problems," Management Science, X, no. 2 (1964), 225Ä248.

7    Lin, Shen.  "Computer Solutions of the Travelling Salesman Problem," Bell
System Technical Journal, XLIV, no. 10 (1965), 2245Ä2269.

8    Little, John D. C., Katta G. Murty, Dura W. Sweeney, and Caroline Karel.
"An Algorithm for the Traveling Salesman Problem," Operations Research, XI,
no. 6 (1963), 972Ä989.

9    Roberts, S. M. and Benito Flores.  "An Engineering Approach to the 
Travelling Salesman Problem," Management Science, XIII, no. 3 (1967), 269Ä288.

10   Rosenkrantz, Daniel J., Richard E. Stearns, and Philip M. Lewis II.  "An 
Analysis of Several Heuristics for the Traveling Salesman Problem," SIAM 
Journal on Computing, VI, no. 6 (1977), 563Ä581.
