RESUME                                                               20 Feb 89

Kevin E. Knauss
2045 CG/AUM
Andrews AFB, MD  20331
(301) 981Ä4978
FAX: (301) 981-4246 (3M EMT 9165)

Kevin E. Knauss is an computerÄcommunications systems officer in the US Air
Force.  In this capacity, he has worked as a consultant on computer system
upgrades for the Space Shuttle Program at Cape Canaveral AFS, FL, for the
Military Personnel Center in San Antonio, TX, and for the Air Rescue Command
Center near St Louis, MO.  He is currently assigned as the software engineer
in charge of the computerÄcontrolled ground communications network for Air
Force One.

Before entering the military, Kevin spent several years as a systems
programmer which included C programming on UNIX.  After receiving his Master
of Science Degree in Industrial Engineering from Lehigh University, he taught
C programming as an Assistant Professor of Computer Science at a junior
college in Pennsylvania.  His quest for finding a solution to the Traveling
Salesman Problem began in 1978 at Lehigh University and continued through his
PhD level courses taken recently at the University of Oklahoma.
