/*
        HEADER:         CUG000.11;
        TITLE:          TSP (header);
        DATE:           Mar 89;
        DESCRIPTION:    Traveling Salesman Problem Header File;
        VERSION:        2.0;
        FILENAME:       TSP.H;
        SEE-ALSO:       TSP.C, NN.C, POPT.C, 2OPT.C, HYBRID.C, 3OPT.C, FN.C,
                        BOOLEAN.H, NODELIST.H,
                        BLDMTX.C, PRTMTX.C, TIME.C;
        AUTHORS:        Kevin E. Knauss;
*/

#define MAXLINE      80
#define MAXCOLS      50
#define MAXROWS      50
#define MAXCARD   65535
