#DEFINE	NOBJ	7	/* plane,gun,bullet,boom,obj1,obj2 and dummy object */
#DEFINE	CENTER	128
#DEFINE	PLANE	0
#DEFINE	GUN	1
#DEFINE	BULLET	2
#DEFINE	BOOM	3
#DEFINE	OBJ1	4
#DEFINE	OBJ2	5
 
#DEFINE	TARGET	1	/* target class */
 
#DEFINE	PLNX0	10	/* Initial plane position and velocity */
#DEFINE	PLNY0	8
#DEFINE	VPLNX	2
#DEFINE	PLNXM	240	/* maximum x position for plane */
#DEFINE	GUNXMX	248
#DEFINE	GUNYMX	184
#DEFINE	BULXMX	248
#DEFINE	BULYMX	184
#DEFINE	JOYMIN	24
#DEFINE	JOYMAX	40
#DEFINE	SWPORT	65280	/* Port location for input switches */
#DEFINE	SWTL	2	/* Left switch bit mask */
#DEFINE	SWTR	1	/* Right switch biy mask	*/
#DEFINE	NTICKS	2	/* Number of clock ticks before page update */

			flag = NULL;
			proc = pchase ;
		    }
		else i