#define UP_RIGHT 0x01
#define RIGHT_UP 0x02
#define RIGHT_DOWN 0x04
#define DOWN_RIGHT 0x08
#define DOWN_LEFT 0x10
#define LEFT_DOWN 0x20
#define LEFT_UP 0x40
#define UP_LEFT 0x80

#define UPPER_HALF 0xc3
#define LOWER_HALF 0x3c
#define LEFT_HALF 0xf0
#define RIGHT_HALF 0x0f

void Circle(), Arc1(), Arc2(), FillCircle();
void Ellipse(), Earc1(), Earc2(), FillEllipse();

