***************   XYAM online command summary
a:
b:              ;change to a or b drive
type afn ...    ;type one or more files (ambiguous file nameS)
list afn ...    ;type one or more files (ambiguous file nameS)
s ufn           ;send (`ala XMODEM) file
r ufn           ;receive (`ala XMODEM) file
dir afn ...     ;alphabetized directory
dirr afn ...    ;directory with transmission time
chat		;opens a link to the console.
bye
^C              ;exit to CP/M (no type or list command in cp/m -use xyam)
******************************************************************************
* PLEASE NOTE: this system is running with a flakey bios, for which I don't  *
* have usable sources.  IF you get a bad sector error, please ^C a few       *
* times. if you do anything else, the directory may become fubar, and you    *
* hackers know what that means!                                              *
******************************************************************************
For more, 'type b:yamdoc.fin' or download one of the yamdoc.* files on b:
a:
b:              ;change to a or b drive
type afn ...    ;type one or more fi