[JUGPDS.FRM]

       CONTRIBUTION FORM FOR JUG-CP/M LIBRARY

NAME: [Masahiro Miyao]           DATE: [Mar/05/84]

ADDRESS: [3-33, 1-23-3 Johoku]

CITY: [Hamamatsu]     PREFECTURE: [Shizuoka]   ZIP: [432]

PHONE : [0534-55-0800 (eves)]

NAME OF PROGRAM, PROCEDURE, OR MODULE (CIRCLE ONE)



SOURCE LANGUAGE: [Relocatable Macro Assembly (MAC or RMAC)
		 Pascal/MT+, BDS C]
  
SYSTEM REQUIRED: [Any CP/M-80 V.2.2 or above]

MEMORY REQUIRED: ..........k Byte

OTHERS ..................................................

DESCRIPTION OF WHAT IT DOES: [See -CATALOG.003.]

HOW TO USE IT:	
	[Read *.DOC files.]

Please attach all relevant documentation and a diskette containing
the source, assembly/compilation/linkage command files, object code,
and any other machine readable documentation. Please use the following
file extensions:

       .ASM      Assembly source file or .BAS, .Z80, .FOR, .PAS, etc.
       .DOC      Documentation
       .COM      Object code for CP/M-80
       .CMD      Object code for CP/M-86
       .EXE      Executable code for MS-DOS

The submitted files are in their present revision level,

       ....      TO THE BEST OF MY KNOWLEDGE CURRENTLY IN PUBLIC DOMAIN

       ....      UNDER MY DIRECT CONTROL HEREBY PLACED INTO THE PUBLIC
                 DOMAIN. PERMISSION IS HEREBY GRANTED TO JUG-CP/MS TO
                 DISTRIBUTE THE FILES FREELY FOR NON-COMMERCIAL
                 PERSONAL USE.

                 SIGNED................................

                 DATE..................................


Please send all materials to:

       JUG-CP/M
       Manyou Bldg. 4F
       3-53-3 Minami-Otsuka 
       Toshima-ku, Tokyo 171
       Japan
       
