cugcpio.obj:	cugcpio.c environ.h
    cl -c cugcpio.c

sectrd.obj:	sectrd.c
    cl -c sectrd.c

sectwr.obj:	sectwr.c
    cl -c sectwr.c

os2rdsct.obj:	os2rdsct.c
    cl -c os2rdsct.c

os2wrsct.obj:	os2wrsct.c
    cl -c os2wrsct.c

sectrd.exe:	sectrd.obj os2rdsct.obj
    cl sectrd.obj os2rdsct.obj

sectwr.exe:	sectwr.obj  os2wrsct.obj
    cl sectwr.obj os2wrsct.obj

cugcpio.exe:	cugcpio.obj
    cl cugcpio.obj \lib\setargv.obj -link /noe
