cugcpio.obj:	cugcpio.c environ.h
    cl -qc -c cugcpio.c

sectrd.obj:	sectrd.c
    cl -qc -c sectrd.c

sectwr.obj:	sectwr.c
    cl -qc -c sectwr.c

rdsct.obj:	rdsct.asm
    masm -ml rdsct;

wrsct.obj:	wrsct.asm
    masm -ml wrsct;

sectrd.exe:	sectrd.obj rdsct.obj
    cl -qc sectrd.obj rdsct.obj

sectwr.exe:	sectwr.obj  wrsct.obj
    cl -qc sectwr.obj wrsct.obj

cugcpio.exe:	cugcpio.obj
    cl -qc cugcpio.obj \lib\setargv.obj -link /noe
