#
cpu =
cflags = /DLINT_ARGS
lflags =
#
ov.exe : ov.obj ovtty.obj ovfmove.obj ovfile.obj ovcmd.obj ovsort.obj ovview.obj
       link $(lflags) /stack:4096 /map @ov.lnk
       rename ov.exe ovup.exe
       exepack ovup.exe ov.exe
       del ovup.exe
ov.exe : ovdir.obj ovmenu.obj ovfdisp.obj file.obj volume.obj string.obj date.obj
ov.exe : ovtag.obj ovattrib.obj direct.obj ovprompt.obj ovwin.obj ovstr.obj
ov.exe : ovselect.obj grabbrk.obj ovhelp.obj ovlogo.obj ovdef.obj farmem.obj
ov.exe : pathopen.obj ovvbuf.obj fileio.obj biosio.obj scantree.obj pathname.obj
ov.obj ovfile.obj ovfmove.obj ovcmd.obj ovsort.obj ovview.obj ovtty.obj : ov.h
ovdir.obj ovmenu.obj ovfdisp.obj ovtag.obj ovattrib.obj ovprompt.obj : ov.h
ovwin.obj ovselect.obj ovhelp.obj ovlogo.obj ovdef.obj : ov.h
ovvbuf.obj pathopen.obj scantree.obj pathname.obj : ov.h
ovfile.obj ovdir.obj file.obj scantree.obj : dosfile.h
#
cvthlp.exe : cvthlp.obj getopt.obj
       link cvthlp+getopt;
#
#     default rules
#
.c.obj:
        cl -c $(cflags) $(cpu) $*.c
.c.exe:
        cl -c $(cflags) $(cpu) $*.c
        link $*;
.asm.obj:
        masm $*;
.asm.exe:
        masm $*;
        link $*;
.asm.com:
        masm $*;
        link $*;
        exe2bin $*.exe $*.com
.obj.exe:
        link $*;
.obj.com:
        link $*;
        exe2bin $*.exe $*.com
.exe.com:
        exe2bin $*.exe $*.com
