
/*
    These are the definitions for the parameter
    vector which is filled in by the argument()
    function.
*/

#define MAXVECTOR 32
#define IMMEDIATE 0
#define DRIVE 1
#define DIRECTBOOT 2
#define BOOTADRESS 3
#define PATCH 4
#define PATCHADRESS 5
#define AUTOPATCH 6
#define NOCHECK 7
#define ISBOOT 8
#define TEST 9
#define PATCHBYTE 10
#define MAXPATCH 16

#define EOL 0

