command /c toollink SORT
command /c toollink CHANGE
command /c toollink FIND0
command /c toollink FIND1
command /c toollink FRQNCY
command /c toollink KWIC
command /c toollink UNIQUE
command /c toollink MACRO
command /c toollink UNROT
command /c toollink FORMAT
command /c toollink MSORT
command /c toollink ARCHIVE
command /c toollink COMPARE
command /c toollink COMPRESS
command /c toollink CONCAT0
command /c toollink CONCAT1
command /c toollink COUNT
command /c toollink CRYPT0
command /c toollink CRYPT1
command /c toollink DETAB
command /c toollink ENTAB
command /c toollink EXPAND
command /c toollink OVERSTRK
command /c toollink TRANSLIT

