The home board for FWKCS(TM) support is The Invention Factory BBS. 
Telephone service has been upgraded since the release of FWKCS Ver. 
1.17, to provide additional fiber optic links. In doing this, the 
telephone company changed some of the phone numbers. Here is the 
current list:
"

                THE INVENTION FACTORY BULLETIN BOARD SYSTEM

             Official logon data telephone numbers as of 06/30/92.

 212-274-8110  Orders only & new users browse #. Hunts to all other lines.
 212-274-8930  Public Access registered users only number. (Single line.)

 212-274-8110  HAYES 2400 baud (10 modem hunt group)
 212-274-8111  ALTERNATE HAYES 2400 baud (10 modem hunt group)

 212-274-8118  HAYES 9600 baud V.42 (12 modem hunt group)
 212-274-8119  ALTERNATE HAYES 9600 baud V.42 (12 modem hunt group)

 212-274-8390  USROBOTICS V.32 Courier HSTs (10 modem hunt group)
 212-274-8391  ALTERNATE USROBOTICS V.32 Courier HSTs (10 modem hunt group)

 212-274-1243  COMPUCOM 9600 V.32/bis.  (12 modem hunt group)
 212-274-1244  ALTERNATE COMPUCOM 9600 V.32/bis.  (12 modem hunt group)

 --------------------------------------------------------------------------
"
