CFLAGS=-O
LDFLAGS=-s
OBJS=alloc.o file.o libmtch.o robj.o iset.o prin.o heur.o main.o conv.o
SHAREDLIB=/lib/shlib.ifile /lib/crt0s.o

dis:	$(OBJS)
	$(LD) $(LDFLAGS) -o dis $(OBJS) $(SHAREDLIB) -lld

$(OBJS):	unc.h
