.ig XMERGE2.TST        VERS:- 01.00  DATE:- 09/26/86  TIME:- 09:37:39 PM
.. Test file consisting of several CAS abstracts for use in trials
..	of xmerger (CAS abstracts are the default option):
..		Usage: xmerger  <xmerge1.tst  xmerge2.tst  +results_file
*
XMERGE2.TST         ANSWER 2 OF 8
 
AN  CA94(21):172080h
TI  Renal sodium excretion in acutely hypophysectomized rats with
    expanded extracellular fluid volume
AU  Bencsath, Pal; Szenasi, Gabor; Ponec, Jozef; Takacs, Lajos;
    Lichardus, Branislav
SO  Dev. Endocrinol., 10(Horm. Regul. Sodium Excretion), 299-305
PY  1980
*
XMERGE2.TST         ANSWER 4 OF 8
 
AN  CA93(13):127840z
TI  Volume changes associated with hydrolysis of ATP by teleost branchial
    (sodium-potassium ion)-dependent ATPase and magnesium(2+)-dependent
    ATPase
AU  Pfeiler, Edward
SO  J. Exp. Zool., 212(2), 291-9
PY  1980
*
XMERGE2.TST         ANSWER 6 OF 8
 
AN  CA91(21):172652j
TI  Volume flows across gallbladder epithelium induced by small
    hydrostatic and osmotic gradients
AU  Van Os, Carel H.; Wiedner, Guenther; Wright, Ernest M.
SO  J. Membr. Biol., 49(1), 1-20
PY  1979
*
XMERGE2.TST         ANSWER 8 OF 8
 
AN  CA73(25):128345r
TI  Quantitative relation between hydrostatic pressure gradient,
    extracellular volume, and active sodium transport in the epithelium
    of the frog skin (R[ana] temporaria)
AU  Voute, C. L.; Ussing, Hans H.
SO  Exp. Cell Res., 62(2-3), 375-83
PY  1970
*
