.ig XSORT.TST        VERS:- 01.00  DATE:- 09/26/86  TIME:- 09:37:53 PM
.. Test file consisting of several CAS abstracts for use in trials
..	of xsortr (CAS abstracts are the default option):
..		Usage: xsortr  xsort.tst  +results_file
..
.. XSORT.TST consists of XMERGE2.TST appended to XMERGE1.TST with an extra
..	record; thus it is unsorted with duplicate records. 
*
XMERGE1.TST         ANSWER 1 OF 8
 
AN  CA103(23):193943m
TI  Steady-state voltages, ion fluxes, and volume regulation in syncytial
    tissues
AU  Mathias, Richard T.
SO  Biophys. J., 48(3), 435-48
PY  1985
*
XMERGE1.TST         ANSWER 2 OF 8
 
AN  CA94(21):172080h
TI  Renal sodium excretion in acutely hypophysectomized rats with
    expanded extracellular fluid volume
AU  Bencsath, Pal; Szenasi, Gabor; Ponec, Jozef; Takacs, Lajos;
    Lichardus, Branislav
SO  Dev. Endocrinol., 10(Horm. Regul. Sodium Excretion), 299-305
PY  1980
*
XMERGE1.TST         ANSWER 3 OF 8
 
AN  CA94(11):81042f
TI  A theoretical model of protein, fluid, and small molecule transport
    in the lung
AU  Harris, Thomas R.; Roselli, Robert J.
SO  J. Appl. Physiol.:  Respir., Environ. Exercise Physiol., 50(1), 1-14
PY  1981
*
XMERGE1.TST         ANSWER 4 OF 8
 
AN  CA93(13):127840z
TI  Volume changes associated with hydrolysis of ATP by teleost branchial
    (sodium-potassium ion)-dependent ATPase and magnesium(2+)-dependent
    ATPase
AU  Pfeiler, Edward
SO  J. Exp. Zool., 212(2), 291-9
PY  1980
*
XMERGE1.TST         ANSWER 5 OF 8
 
AN  CA93(5):42670u
TI  Effect of collagenase and ouabain on renal cell volume in hypotonic
    media
AU  Linshaw, Michael A.; Grantham, Jared J.
SO  Am. J. Physiol., 238(6), F491-F498
PY  1980
*
XMERGE1.TST         ANSWER 6 OF 8
 
AN  CA91(21):172652j
TI  Volume flows across gallbladder epithelium induced by small
    hydrostatic and osmotic gradients
AU  Van Os, Carel H.; Wiedner, Guenther; Wright, Ernest M.
SO  J. Membr. Biol., 49(1), 1-20
PY  1979
*
XMERGE1.TST         ANSWER 7 OF 8
 
AN  CA91(9):70197x
TI  Cell volume regulation
AU  Janacek, Karel
SO  Biophys. Membr. Transp., 2, 33-52
PY  1977
*
XMERGE1.TST         ANSWER 8 OF 8
 
AN  CA73(25):128345r
TI  Quantitative relation between hydrostatic pressure gradient,
    extracellular volume, and active sodium transport in the epithelium
    of the frog skin (R[ana] temporaria)
AU  Voute, C. L.; Ussing, Hans H.
SO  Exp. Cell Res., 62(2-3), 375-83
PY  1970
*
XMERGE1.TST         ANSWER 7 OF 8
 
AN  CA91(9):70197x
TI  Cell volume regulation
AU  Janacek, Karel
SO  Biophys. Membr. Transp., 2, 33-52
PY  1977
KW  cell vol regulation calcium water; osmoregulation calcium water
    regulation
*
XMERGE2.TST         ANSWER 2 OF 8
 
AN  CA94(21):172080h
TI  Renal sodium excretion in acutely hypophysectomized rats with
    expanded extracellular fluid volume
AU  Bencsath, Pal; Szenasi, Gabor; Ponec, Jozef; Takacs, Lajos;
    Lichardus, Branislav
SO  Dev. Endocrinol., 10(Horm. Regul. Sodium Excretion), 299-305
PY  1980
*
XMERGE2.TST         ANSWER 4 OF 8
 
AN  CA93(13):127840z
TI  Volume changes associated with hydrolysis of ATP by teleost branchial
    (sodium-potassium ion)-dependent ATPase and magnesium(2+)-dependent
    ATPase
AU  Pfeiler, Edward
SO  J. Exp. Zool., 212(2), 291-9
PY  1980
*
XMERGE2.TST         ANSWER 6 OF 8
 
AN  CA91(21):172652j
TI  Volume flows across gallbladder epithelium induced by small
    hydrostatic and osmotic gradients
AU  Van Os, Carel H.; Wiedner, Guenther; Wright, Ernest M.
SO  J. Membr. Biol., 49(1), 1-20
PY  1979
*
XMERGE2.TST         ANSWER 8 OF 8
 
AN  CA73(25):128345r
TI  Quantitative relation between hydrostatic pressure gradient,
    extracellular volume, and active sodium transport in the epithelium
    of the frog skin (R[ana] temporaria)
AU  Voute, C. L.; Ussing, Hans H.
SO  Exp. Cell Res., 62(2-3), 375-83
PY  1970
*
