.ig XSRCH.TST        VERS:- 01.00  DATE:- 09/26/86  TIME:- 09:37:59 PM
.. Test file consisting of several CAS abstracts for use in trials of xsrchr
..	(CAS abstracts are the default option if XSRCH.ZIP = XSRCHCAS.ZIP):
..
..	Usage: xsrchr  xsrch.tst  +results_file
..		[the program then enters full screen input - 
..			it is setup for condensing CAS files -
..			enter ESC to continue]
..
..	XSRCHR extracts condensed files like XMERGE1.TST, etc, from
..		full abstract files. 
..	XSRCHR also can extract records satisfying specific search strings.
*
ANSWER 1 OF 5
 
AN  CA103(25):209170v
TI  Hydrogen-bonding networks in bacteriorhodopsin may afford a proton
    pathway and structural stability
AU  Rosenbusch, J. P.
CS  Eur. Mol. Biol. Lab.
LO  Heidelberg 6900, Fed. Rep. Ger.
SO  Bull. Inst. Pasteur (Paris), 83(3), 207-20
SC  6-3 (General Biochemistry)
DT  J
CO  BIPAA8
IS  0020-2452
PY  1985
LA  Eng
AB  A structure of bacteriorhodopsin is proposed that may explain
    functional and structural properties which have not been previously
    accounted for.  Its pattern is derived uniquely from the
    identification of turn regions as shown by C. Paul and J. P.
    Rosenbusch (1985).  Significantly more polar and potentially ionized
    groups would be contained in the hydrophobic domain of the membrane
    than previously assumed, and would form extensive networks of H
    bonds.  Criteria for residues which may contribute to proton
    conduction, combined with topol. considerations, suggest specific
    linear proton pathways that span the entire membrane in discrete
    steps.  Two examples are presented, both of which comprise carboxyl
    and tyrosyl residues as paôh÷ay ãïnstituents and include the
    retinal-linked lysine.  The proximities of the groups involved as
    well as the very short helix-linking segments impose stringent topol.
    criteria.  This allows probing of whether the proposed dense
    H-bonding systems could afford satn. of all donor and acceptor
    groups.  Irresp. of detailed assignments, such satn. appears
    possible.  H bonds within and between helixes could explain the
    unusual stability of bacteriorhodopsin and could also account for
    interactions between monomers, allowing their assocn. to purple
    membranes.  Although this working hypothesis appears to offer
    plausible interpretations for several crit. properties of
    bacteriorhodopsin, it is likely to be as resistant to unequivocal
    proof as previously proposed models.  Before the structure is known
    at at. resoln., however, the notion of extensive H bonding within
    hydrophobic domains in the protein and membrane interior may
    nonetheless refresh the concepts of the principles governing membrane
    protein structure.
KW  bacteriorhodopsin structure model function; hydrogen bond network
    bacteriorhodopsin; membrane protein hydrogen bond network
IT  Halobacterium halobium
       (bacteriorhodopsin of, hydrogen-bond network in, protein structure
       and function in relation to)
IT  Bacteriorhodopsins
       (hydrogen bond network in, hydrogen ion transport and monomer
       assocn. in relation to)
IT  Proteins
       (membranes, hydrogen-bond network in, structure and function at)
IT  Hydrogen bond
       (network, in bacteriorhodopsin, hydrogen ion transport and monomer
       assocn. in relation to)
IT  Conformation and Conformers
    Molecular structure, natural product
       (of bacteriorhodopsin, hydrogen-bond network in, membrane protein
       structure and function in relation to)
IT  Biological transport
       (of hydrogen ions, by bacteriorhodopsin, hydrogen-bond network in,
       membrane protein structure and function in relation to)
IT  12408-02-5, biological studies
       (transport of, by bacteriorhodopsin, hydrogen-bond network in
       relation to)
 
*
ANSWER 2 OF 5
 
AN  CA102(5):41618a
TI  On the role of hydrogen bonds and hydrogen-bonded systems with large
    proton polarizability for mechanisms of proton activation and
    conduction in bacteriorhodopsin
AU  Zundel, G.; Merz, H.
CS  Inst. Phys. Chem., Univ. Munich
LO  Munich D-8000/2, Fed. Rep. Ger.
SO  Prog. Clin. Biol. Res., 164(Inf. Energy Transduction Biol. Membr.),
    153-64
SC  6-0 (General Biochemistry)
SX  10
DT  J
CO  PCBRD2
IS  0361-7742
PY  1984
LA  Eng
AB  A review with 45 refs.  H bonds and H-bonded chains with large proton
    polarizability are of decisive importance, both for the activation of
    protons and the conduction of the pos. charge in bacteriorhodopsin.
KW  review bacteriorhodopsin proton transfer hydrogen; hydrogen bond
    bacteriorhodopsin pump review
IT  Hydrogen bond
       (in proton transport by bacteriorhodopsin)
IT  Bacteriorhodopsins
       (proton transport in, hydrogen bonds and hydrogen-bonded systems
       in)
IT  12408-02-5, biological studies
       (transport of, in bacteriorhodopsin, hydrogen bonds and
       hydrogen-bonded systems in)
 
*
ANSWER 3 OF 5
 
AN  CA97(23):194653m
TI  Light-induced aldimine bond migration as a possible mechanism for
    proton transfer in bacteriorhodopsin
AU  Ovchinnikov, Yu. A.; Abdulaev, N. G.
CS  Shemyakin Inst. Bioorg. Chem.
LO  Moscow 117988, USSR
SO  Membr. Transp., Volume 2, 319-22.  Edited by: Martonosi, Anthony N.
    Plenum: New York, N. Y.
SC  6-1 (General Biochemistry)
DT  C
CO  48ETAH
PY  1982
LA  Eng
AB  The light-driven proton-transporting mechanism of bacteriorhodopsin
    (BR) in membranes appears to involve proton-specific channels formed
    by chains of H bonds within the mol.  This mechanism is supported by
    exptl. studies on aldimine bond migration occurring during the BR
    photocycle in which retinal covalently attached to the .epsilon.-NH2
    group of lysine-41 (Lys-41) in the dark migrates to Lys-215 on
    illumination.  The protonation and deprotonation of retinal aldimines
    in different microenvironments of BR is advantageous for proton
    transport across the purple membrane.
KW  bacteriorhodopsin photocycle aldimine proton transport
IT  Light, biological effects
       (aldimine bond migration in bacteriorhodopsin induced by, hydrogen
       ion transport in relation to)
IT  Bacteriorhodopsins
       (aldimine bond migration in photocycle of, hydrogen ion transport
       in relation to)
IT  Hydrogen bond
       (of bacteriorhodopsin, photocycle effect on, hydrogen ion
       transport in relation to)
IT  Biological transport
       (of hydrogen ion, by purple membrane in bacteriorhodopsin
       photocycle, aldimine bond migration in relation to)
IT  Cell membrane
       (purple, bacteriorhodopsin hydrogen bonding in, photocycle effect
       on)
IT  116-31-4
       (migration of, in bacteriorhodopsin photocycle, hydrogen ion
       transport in relation to)
IT  12408-02-5, biological studies
       (transport of, by purple membrane in bacteriorhodopsin photocycle,
       aldimine bond migration in relation to)
 
*
ANSWER 4 OF 5
 
AN  CA95(19):164133h
TI  Proton conduction in bacteriorhodopsin via a hydrogen-bonded chain
    with large proton polarizability
AU  Merz, Helmut; Zundel, Georg
CS  Phys.-Chem. Inst., Univ. Muenchen
LO  Munich D-8000/2, Fed. Rep. Ger.
SO  Biochem. Biophys. Res. Commun., 101(2), 540-6
SC  6-3 (General Biochemistry)
DT  J
CO  BBRCA9
IS  0006-291X
PY  1981
LA  Eng
AB  A Corey-Pauling-Kolthun mol. model of bacteriorhodopsin was built.
    This model shows that a largely structurally sym. H-bonded chain
    Asp-Tyr-Tyr-Tyr-Tyr-Tyr-Tyr-Glu may be formed.  With regard to the
    total proton potential this chain shows very large proton
    polarizability and thus via this chain the pos. charge can be
    conducted to the outside of the membrane via a Grotthus mechanism.
KW  bacteriorhodopsin proton transport hydrogen bond
IT  Bacteriorhodopsins
       (hydrogen ion transport by, hydrogen-bonded peptide chain in
       relation to)
IT  Hydrogen bond
       (of peptide chain, of bacteriorhodopsin, hydrogen ion transport in
       relation to)
IT  12408-02-5, biological studies
       (transport of, in bacteriorhodopsin, hydrogen-bonded peptide chain
       in relation to)
 
*
ANSWER 5 OF 5
 
AN  CA94(15):116126r
TI  Molecular models of proton pumps
AU  Nagle, J. F.; Mille, M.
CS  Dep. Phys., Carnegie-Mellon Univ.
LO  Pittsburgh, PA 15213, USA
SO  J. Chem. Phys., 74(2), 1367-72
SC  6-1 (General Biochemistry)
DT  J
CO  JCPSA6
IS  0021-9606
PY  1981
LA  Eng
AB  Three theor. models of proton pumps are discussed at the mol. level.
    The models contain H bonded chains, which are the best understood
    channels, structurally and kinetically, for proton conduction within
    membranes.  The 1st model, called the integral injector model, has an
    active site which involves a pK change.  The 2nd model, called the
    switch model, utilizes a conformational change in a retinal as the
    active site.  The 3rd model, called the active chain model, involves
    a conformational change in the protein, and the active site is
    delocalized to include the entire H-bonded chain.  The models
    presented were chosen in part because of their possible relevance to
    the bacteriorhodopsin proton pump and are compared with this system,
    but the basic principles involved have greater generality.  They were
    chosen to explore the general family of theor. proton pumps.  Each
    model illustrates general principles that form a basis for generating
    addnl. models in the family.
KW  proton pump membrane model; bacteriorhodopsin proton pump model
IT  Chains, chemical
       (conformational transitions of, of proton pump protein,
       mechanistic model in relation to)
IT  Hydrogen bond
       (in proton pump models)
IT  Biological transport
       (of hydrogen ion, mechanism of, model of)
IT  Conformational inversion
       (of retinal, proton pump mechanism in relation to)
IT  Bacteriorhodopsins
       (proton transport by, mechanism of, models of)
IT  Membranes and Diaphragms
       (biol., proton transport by, mechanism of, models of)
IT  12408-02-5, biological studies
       (transport of, model of)

