\lst\parser\parse \lst\prelude\class.st >class.p
\lst\parser\parse \lst\prelude\object.st >object.p
\lst\parser\parse \lst\prelude\string.st >string.p
\lst\parser\parse \lst\prelude\larray.st >larray.p
\lst\parser\parse \lst\prelude\nil.st >nil.p
\lst\parser\parse \lst\prelude\array.st >array.p
\lst\parser\parse \lst\prelude\boolean.st >boolean.p
\lst\parser\parse \lst\prelude\true.st >true.p
\lst\parser\parse \lst\prelude\false.st >false.p
\lst\parser\parse \lst\prelude\block.st >block.p
\lst\parser\parse \lst\prelude\symbol.st >symbol.p
\lst\parser\parse \lst\prelude\magnitud.st >magnitud.p
\lst\parser\parse \lst\prelude\number.st >number.p
\lst\parser\parse \lst\prelude\integer.st >integer.p
\lst\parser\parse \lst\prelude\char.st >char.p
\lst\parser\parse \lst\prelude\float.st >float.p
\lst\parser\parse \lst\prelude\radian.st >radian.p
\lst\parser\parse \lst\prelude\point.st >point.p
\lst\parser\parse \lst\prelude\random.st >random.p
\lst\parser\parse \lst\prelude\collecti.st >colllecti.p
\lst\parser\parse \lst\prelude\bag.st >bag.p
\lst\parser\parse \lst\prelude\set.st >set.p
\lst\parser\parse \lst\prelude\kcollect.st >kcollect.p
\lst\parser\parse \lst\prelude\dictiona.st >dictiona.p
\lst\parser\parse \lst\prelude\scollecti.st >scollecti.p
\lst\parser\parse \lst\prelude\interval.st >interval.p
\lst\parser\parse \lst\prelude\list.st >list.p
\lst\parser\parse \lst\prelude\acollect.st >acollect.p
\lst\parser\parse \lst\prelude\file.st >file.p
\lst\parser\parse \lst\prelude\bytearra.st >bytearra.p
\lst\parser\parse \lst\prelude\semaphor.st >semaphor.p
\lst\parser\parse \lst\prelude\process.st >process.p
\lst\parser\parse \lst\prelude\smalltal.st >smalltal.p
copy *.p+init standard


