ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
บ   This is a DEMO form     			Program V. 1.0		     บ
วฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤถ
บ									     บ
บ									     บ
บ									     บ
บ	€ 1. SELECT TESTS						     บ
บ	€ 2. SYSTEM CONSTANTS / OPTIONS					     บ
บ	€ 3. DOWNLOAD TEST PROGRAM					     บ
บ	€ 4. REVIEW ERROR LOG						     บ
บ	€ 5. CONTINUE TESTING						     บ
บ	€ 6. RUN NEW SERIES OF TESTS					     บ
บ									     บ
บ	X. EXIT TO MS-DOS						     บ
บ									     บ
บ				       €				     บ
บ									     บ
บ									     บ
บ									     บ
บ									     บ
บ									     บ
ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
