#$cc
#    cpp %1.c %1.i -Ml
#    msc %1.i/I\headers\ms/I\headers/AL; >error.c$$
#    if result
#	delete %1.i
#	edit %1.c -eerror.c$$
#	delete error.c$$
#	abort
#    endif
#    delete %1.i
#    delete error.c$$

BIN = $(SYSDRIVE)\bin.dos

.c.obj :
	cl -c -AL $<

cpp.exe : cpp1.obj cpp2.obj cpp3.obj cpp4.obj cpp5.obj cpp6.obj
	link cpp1+cpp2+cpp3+cpp4+cpp5+cpp6,cpp,NUL,/NOI /STACK:4096
	copy cpp.exe $(BIN)


