: cp-ged.bat - 12/05/87
:
echo off
:
vkette
:
copy   ALL.BAT       a:
copy   CP-GED.BAT    a:
copy   CT.BAT        a:
copy   ELINK.BAT     a:
copy   LINKT.BAT     a:
copy   MLINK.BAT     a:
copy   QC1.BAT       a:
copy   QCC.BAT       a:
copy   T.BAT         a:
copy   TC.BAT        a: 
:  
copy   MLNK.DAT      a:
copy   ELNK.DAT      a:
:                    
copy   GED.DOC       a:
copy   CONVERT.ME    a:
:                       
copy   GED.EXE             a:
copy   \EXE\LS.EXE         a:
copy   \EXE\MORE.EXE       a:
copy   \EXE\GREP2.EXE      a:
:
copy   GEDIO.A       a:
copy   GEDIO.ASM     a:
:                    
copy   GEDIO.O       a:
copy   GEDIO.OBJ     a:
:                    
copy   GED.H         a:
copy   GED.C         a:
copy   GED1.C        a:
copy   GED2.C        a:
copy   GED3.C        a:
copy   GED4.C        a:
copy   GED5.C        a:
copy   GED6.C        a:
copy   GED7.C        a:
copy   GED8.C        a:
copy   GED9.C        a:
copy   GED10.C       a:
copy   GED11.C       a:
:
vkette  /q
:
a:
last
c:
