: ct.bat - 08/31/87
: mass compile for turbo-c
:
erase ct.lst
:
cc -c -DTC  ged.c >>  ct.lst
:
cc -c -DTC  ged1.c >> ct.lst
:
cc -c -DTC  ged2.c >> ct.lst
:
cc -c -DTC  ged3.c >> ct.lst
:
cc -c -DTC  ged4.c >> ct.lst
:
cc -c -DTC  ged5.c >> ct.lst
:
cc -c -DTC  ged6.c >> ct.lst
:
cc -c -DTC  ged7.c >> ct.lst
:
cc -c -DTC  ged8.c >> ct.lst
:
cc -c -DTC  ged9.c >> ct.lst
:
cc -c -DTC  ged10.c >> ct.lst
:
cc -c -DTC  ged11.c >> ct.lst
:
beep








