
/* msc_hdrs.h is the usual band of header files for microsoft c progs */

#ifndef MSC_HDRS_H
#define MSC_HDRS_H


#include <ctype.h>
    #undef tolower      /* don't let these be defined as macros */
    #undef toupper
#include <stdio.h>
#include <math.h>
#include <string.h>
#include <fcntl.h>
#include <types.h>
#include <stat.h>
#include <io.h>
#include <stdlib.h>
#include <conio.h>
#include <dos.h>
#include <time.h>
#include <process.h>
#include <memory.h>
#include <malloc.h>

#endif

