#---------------------------------------------------------------------
#	HOC3 makefile for UNIX-like 'make' utility.

PROGRAM		= hoc3.exe

.SUFFIXES:
.SUFFIXES:	.exe .obj .c .y
#		Assume Microsoft C compiler
MSC		= cl
CFLAGS	= -c -Ox -W2
INCL	= -I.
CC		= $(MSC) $(CFLAGS) $(INCL)
YACC	= bison -ld

HEADERS	=	hoc3.h hocdecl.h
SRC		=	hoc3.y init.c math.c symbol.c
OBJS	=	hoc3.obj init.obj math.obj symbol.obj

#		construction rules
.c.obj:
	${CC} $< ;

.y.c:
	${YACC} $<

.y.obj:
	$(YACC) $<
	$(CC) $*.c ;

$(PROGRAM): $(OBJS)
		link $(OBJS),,, /NOI /STACK:0x8000 ;
$(OBJS):	hocdecl.h

# 		not all 'MAKE's infer equally, so this dependency is explicit.
hoc3.c:		hoc3.y
