# makefile for UNIX-like programs v1.5.  Aztec C v3.20d
# David MacKenzie

# Entry points:
# make or make all
#	make all executables
# make arc
#	make archive

CFLAGS=
# Name of your "arc" program.
ARC=pkarc

# These are kludges for arc to bypass MSDOS's 128 char command line limit.
COMS1=cat.com cp.com chmod.com df.com du.com fmt.com ls.com mv.com
COMS2=rm.com strings.com touch.com tr.com vis.com wc.com

DOCS1=cat.doc chmod.doc cp.doc df.doc du.doc fmt.doc ls.doc mv.doc
DOCS2=rm.doc strings.doc touch.doc tr.doc vis.doc wc.doc
DOCS3=makefile readme

SRCS1=cat.c chmod.c cp.c df.c du.c fmt.c ls.c mv.c
SRCS2=rm.c strings.c touch.c tr.c vis.c wc.c
SRCS3=globargs.c getdir.h getdir.asm bytefree.asm

ARCF=\\tmp\\unixpg15.arc

# The dummy target is a zero-length file, "all"
all:	$(COMS1) $(COMS2)
	touch all

arc:	$(ARCF)
	@echo archive complete.

$(ARCF):	$(COMS1) $(COMS2) $(DOCS1) $(DOCS2) $(DOCS3) $(SRCS1) $(SRCS2) $(SRCS3)
	$(ARC) u $(ARCF) $(COMS1)
	$(ARC) u $(ARCF) $(COMS2)
	$(ARC) u $(ARCF) $(DOCS1)
	$(ARC) u $(ARCF) $(DOCS2)
	$(ARC) u $(ARCF) $(DOCS3)
	$(ARC) u $(ARCF) $(SRCS1)
	$(ARC) u $(ARCF) $(SRCS2)
	$(ARC) u $(ARCF) $(SRCS3)

globargs.o:	globargs.c getdir.h
	cc $(CFLAGS) globargs.c -o globargs.o

# cat
cat.com:	cat.o globargs.o getdir.o
	ln cat.o globargs.o getdir.o -lc -o cat.com

# chmod
chmod.com:	chmod.o globargs.o getdir.o
	ln chmod.o globargs.o getdir.o -lc -o chmod.com

# cp
cp.com:	cp.o globargs.o getdir.o
	ln cp.o globargs.o getdir.o -lc -o cp.com

cp.o:	cp.c getdir.h
	cc $(CFLAGS) cp.c -o cp.o

# df
df.com:	df.o bytefree.o
	ln df.o bytefree.o -lc -o df.com

# du
du.com:	du.o globargs.o getdir.o
	ln du.o globargs.o getdir.o -lc -o du.com

du.o:	du.c getdir.h
	cc $(CFLAGS) du.c -o du.o

# fmt
fmt.com:	fmt.o globargs.o getdir.o
	ln fmt.o globargs.o getdir.o -lc -o fmt.com

# ls
ls.com:	ls.o getdir.o
	ln ls.o getdir.o -lc -o ls.com

# Allocate extra space in expression table (default 80).
ls.o:	ls.c getdir.h
	cc $(CFLAGS) -E400 ls.c -o ls.o

# mv
mv.com:	mv.o globargs.o getdir.o
	ln mv.o globargs.o getdir.o -lc -o mv.com

# rm
rm.com:	rm.o globargs.o getdir.o
	ln rm.o globargs.o getdir.o -lc -o rm.com

rm.o:	rm.c getdir.h
	cc $(CFLAGS) rm.c -o rm.o

# strings
strings.com:	strings.o globargs.o getdir.o
	ln strings.o globargs.o getdir.o -lc -o strings.com

# touch
touch.com:	touch.o globargs.o getdir.o
	ln touch.o globargs.o getdir.o -lc -o touch.com

# tr
tr.com:	tr.o
	ln tr.o -lc -o tr.com

# vis
vis.com:	vis.o globargs.o getdir.o
	ln vis.o globargs.o getdir.o -lc -o vis.com

# wc
wc.com:	wc.o globargs.o getdir.o
	ln wc.o globargs.o getdir.o -lc -o wc.com
