     ------------------------------------------------------------

     OverView Registration Form            Version 1.02  1-Mar-87


     To become a registered user of OverView, complete and return
     this form along with a $ 15 license fee.  The license fee
     should be a check or money order, payable in USA funds.


             Send to:     Blue Sky Software
                          P.O. Box 27495
                          Minneapolis, MN 55427
                          U.S.A.


        Name: ___________________________________________________

     Company: ___________________________________________________

     Address: ___________________________________________________

              ___________________________________________________

              ___________________________________________________


     Please accept this registration for OverView version 1.02.
     I agree to your disclaimer of all warranties and the
     restrictions on copying.


     ________________________________________     _______________
                   SIGNED                              DATE


     Please feel free to add any comments, friendly criticisms,
     problem reports, and improvement ideas you might have about
     the product.

                     THANK YOU FOR YOUR SUPPORT!


     ------------------------------------------------------------
