'\" Last Delta     01-26-86
.TH UNDOS 1 OMEN
.SH NAME
undos,tounix,todos,tocpm,tomac,unmac,unparity \- Change
ASCII file format for target operating system
.SH SYNOPSIS
.B undos
[
.B -s
]
file ...
.br
.B tounix
[
.B -s
]
file ...
.br
.B todos
[
.B -s
]
file ...
.br
.B tocpm
[
.B -s
]
file ...
.br
.B unmac
[
.B -s
]
file ...
.br
.B tomac
[
.B -s
]
file ...
.br
.B unparity
file ...
.SH DESCRIPTION
.B Undos
and
.B tounix
convert DOS or CP/M format source files to Unix format by deleting
carriage returns preceding linefeeds and eliminating characters
starting with CPMEOF (^Z).
.PP
.B Todos
converts Unix format source files to DOS format by adding a carriage return
(if not already present) before each linefeed,
and eliminates characters
starting with CPMEOF (^Z).
.B Tocpm
additionally appends CPMEOF (^Z) characters to the resulting file
to make the file length a multiple of the 128 byte CP/M record length.

Any combination of
.B undos, todos,
or
.B tocpm
(without flags)
may be applied to a proper ASCII
file without destroying information.
Lone carriage returns used to force overprinting are not translated
to CR/LF pairs.

.B Unmac
converts files with lines terminated only by carriage return
to Unix format.
.B Unmac
should only be used to translate files whose lines are terminated
by lone carriage returns.

.B Tomac
converts Unix format files to Macintosh format
(lines terminated by carriage return only).

The optional flag
.B -s
Strips the parity bit on all characters
and discards all resulting characters with values less than 7.

.B Unparity
merely strips the parity bit from the files.

The access and modification times of the modified files are set
to those of the original files.
.SH DIAGNOSTICS
Refuses to translate files in which "binary" characters (less than 7
or greater than 127) are seen before CPMEOF.
Refuses to translate files
with ultra long lines.
Refuses to translate special files.
.SH NOTES
Should be executed with the current directory in the same filesystem
as the target files for minimum disk i/o.
.SH BUGS
Does not detect short files without linefeeds.
.B Unmac
and
.B tomac
cannot handle files with CR-only overprinting.
(ASCII allows either LF or CR/LF to delimit lines, but not CR.)
.SH SEE ALSO
lar(1), yam(1), sq(1), usq(1), rb(omen), sb(omen)
