c:\ake\ang -a40 -nd -r9 -d0.3
c:\ake\pictga gang000.out gdan000.tga
c:\ake\pictga gang040.out gdan040.tga
c:\ake\pictga gang080.out gdan080.tga
c:\ake\pictga gang120.out gdan120.tga
c:\ake\pictga gang160.out gdan160.tga
c:\ake\pictga gang200.out gdan200.tga
c:\ake\pictga gang240.out gdan240.tga
c:\ake\pictga gang280.out gdan280.tga
c:\ake\pictga gang320.out gdan320.tga
c:\ake\ang -a40 -nd -r9
c:\ake\pictga gang000.out ggan000.tga
c:\ake\pictga gang040.out ggan040.tga
c:\ake\pictga gang080.out ggan080.tga
c:\ake\pictga gang120.out ggan120.tga
c:\ake\pictga gang160.out ggan160.tga
c:\ake\pictga gang200.out ggan200.tga
c:\ake\pictga gang240.out ggan240.tga
c:\ake\pictga gang280.out ggan280.tga
c:\ake\pictga gang320.out ggan320.tga
c:\ake\ang -a40 -nd -r9 -g256
c:\ake\pictga gang000.out gang000.tga
c:\ake\pictga gang040.out gang040.tga
c:\ake\pictga gang080.out gang080.tga
c:\ake\pictga gang120.out gang120.tga
c:\ake\pictga gang160.out gang160.tga
c:\ake\pictga gang200.out gang200.tga
c:\ake\pictga gang240.out gang240.tga
c:\ake\pictga gang280.out gang280.tga
c:\ake\pictga gang320.out gang320.tga
