;
; abort.mac	by	F. A. Scacchitti	11 - 24 - 84
;
;	abort(error code)
;
EXTRN	EXIT
;
ABORT::
;
	POP	B		; throw away return address
	POP	H		; get abort code
	ORA	A		; code passed ?
	JZ	ABORT2		; no  - leave it as is
	MOV	A,L
	STA	ABCODE		; yes - imbed it in the message
ABORT2:	LXI	D,ABTMSG	; Load abort message
	MVI	C,9
	CALL	5
	JMP	EXIT
;
ABTMSG:	DB	0DH, 'Aborted '
;
ABCODE:	DB	07,0D,'$'
;
	END

