
;
;----- call4.mac   Small-C  arithmetic and logical library
;
;
;	part 4		arithmetic shift routines
;

        ;
        ;SHIFT DE ARITHMETICALLY RIGHT BY HL AND RETURN IN HL
        ;
CCASR:: 
        XCHG
        DCR E
        RM
        MOV A,H
        RAL
        MOV A,H
        RAR
        MOV H,A
        MOV A,L
        RAR
        MOV L,A
        JMP CCASR+1
        ;
        ;SHIFT DE ARITHMETICALLY LEFT BY HL AND RETURN IN HL
        ;
CCASL:: 
        XCHG
        DCR E
        RM
        DAD H
        JMP CCASL+1
        ;
 	END	

