
;----- call1.mac   Small-C  arithmetic and logical library
;	
;	part 1		Multiply Routine
;
                        ;
                        ;        ;
        ;MULTIPLY DE BY HL AND RETURN IN HL
        ;(SIGNED MULTIPLY)
        ;
CCMULT::
MULT:   MOV B,H
        MOV C,L
        LXI H,0
CCMLT1: MOV A,C
        RRC
        JNC CCMLT2
        DAD D
CCMLT2: XRA A
        MOV A,B
        RAR
        MOV B,A
        MOV A,C
        RAR
        MOV C,A
        ORA B
        RZ
        XRA A
        MOV A,E
        RAL
        MOV E,A
        MOV A,D
        RAL
        MOV D,A
        ORA E
        RZ
        JMP CCMLT1
 
	END

