;
;	cpmdisk(disk)
;
;	F. A. Scacchitti 8/4/84
;
CBDOS	EQU	5	;/* bdos entry point */
LF	EQU	10
EOL	EQU	13
;
; CP/M BDOS CALLS 
;
SELECT	EQU	14	;log-in	a drive
;
;
CPMDISK::
	POP	D
	POP	H
	PUSH	H
	PUSH	D
	MOV	A,L			; if(d~=0)
	ORA	H
	JZ	DISKIF1
	XCHG				;	cpm(SELECT,d-1);
	DCX	D
	MVI	C,SELECT
	CALL	CBDOS		; (mod fas)
DISKIF1:
	RET

	END

