
; doldir(source, dest, n)

DOLDIR::
	INX	SP	; Skip over return address
	INX	SP
	POP	B	; Load n
	POP	D	; Load destination
	POP	H	; Load source
	DB	0EDH, 0B0H ; Do	LDIR instruction
	PUSH	H	; Restore stack
	PUSH	D
	PUSH	B
	DCX	SP
	DCX	SP
	RET

	END

