
; lddr(source, dest, n)

DOLDDR::
	INX	SP	; Skip over return address
	INX	SP
	POP	B	; Load n
	POP	D	; Load destination
	POP	H	; Load source
	DB	0EDH, 0B8H ; Do	LDDR instruction
	PUSH	H	; Restore stack
	PUSH	D
	PUSH	B
	DCX	SP
	DCX	SP
	RET

	END

