;
;	freeio(unit)	by	F.A.Scacchitti		9/12/84
;
;	mark a buffer as free.
;
;

;
NBUFS	EQU	8
FCBSIZE	EQU	36	;size, in bytes, of an FCB
BUFFER	EQU	6	;offset	to disk	sector buffer in I/O structure
FLAG	EQU	33	;file-type flag	byte (in unused	part of	FCB)
FREEFLG	EQU	128	;This I/O structure is available for the taking
BUFSIZ	EQU	1024	;how long the sector buffer is
NULL	EQU	0
;

EXTRN	IOBUFS
;
;
FREEIO::				;Mod  6	May 80 rj
	POP	B			;save rtn addr
	POP	H			;get buffer addr
	PUSH	H			;put the stack back together
	PUSH	B
	LXI	D,FLAG			;find flag byte
	DAD	D
	MVI	M,FREEFLG		;mark buffer as	'free'
	LXI	H,NULL			;return	something
	RET
	END

