
; inp(port#)		; Added 2/84 (fas)

INP::
	POP	D	; Skip over return address
	POP	B	; Load port # into C
	DB	0EDH, 068H ; Do <IN L,(C)> instruction
	PUSH	B	; Restore stack
	PUSH	D
	MOV	A,L	; Data was returned in L
	RLC		; Sign extend HL
	SBB	A	;
	MOV	H,A	; That's it
	RET

	END

