
;
;	putlist(c)
;
;	F. A. Scacchitti 8/4/84
;
;
CBDOS	EQU	5	;/* bdos entry point */

LF	EQU	10
EOL	EQU	13
;
; CP/M BDOS CALLS 
;

LSTOUT	EQU	5	;write character to list device

;
;	Storage varibles found in ulink() or ulinq()
;
EXTRN	ZZTEMP
;
;
PUTLIST::
	POP	B
	POP	D
	PUSH	D
	PUSH	B
	SHLD	ZZTEMP
	MVI	C,LSTOUT		; cpm(LSTOUT,c);
	CALL	CBDOS		; (mod to cbdos(fas))
	LDA	ZZTEMP
	CPI	EOL			; if(c==EOL)
	JNZ	PUTLS1
	MVI	E,LF			;	cpm(LSTOUT,LF);
	MVI	C,LSTOUT
	CALL	CBDOS		; (mod to cbdos(fas))
PUTLS1:	LHLD	ZZTEMP			; return(c & 0377)
	MVI	H,0
	RET

	END

