
;	File i/o storage varibles
;
;
ZZUNIT::	DS	2	;I/O structure address to act on
ZZIP::		DS	2	;int *ZZIP;
ZZCHP::		DS	2	;char *ZZCHP;
ZZDP::		DS	2	;char *ZZDP;
ZZFILE::	DS	2	;file name
ZZMODE::	DS	2	;char *mode;(read or write)
ZZCH::		DS	2	;char ch;
ZZT::		DS	2	;int t;
ZZFN::		DS	2	;int ZZFN;	i/o function (for cpmio)
ZZNUBU::	DS	2	;# TEMPORARY BUFFER STORAGE 
ZZMXSC::	DS	1	;# SECTOR COUNTER
ZZSVCH::	DS	2	;char *ZZSVCH;	saved character	pointer

		END
